### ISSUE TITLE
ppl in openai model

### ISSUE THREAD

**Issue by XuandongZhao** [asahi417/lmppl#3]
`            nll.append(sum([i for i in completion['choices'][0]['logprobs']['token_logprobs'] if i is not None]))
`
I think this calculation may be wrong. May need to change to 

`            nll.append(sum([i for i in completion['choices'][0]['logprobs']['token_logprobs'] if i is not None]) / len([i for i in completion['choices'][0]['logprobs']['token_logprobs'] if i is not None]))
`

**Comment by asahi417** [comment]
Thanks! I think you're right. I'll fix it accordingly!
