### ISSUE TITLE
Handling of long input

### ISSUE THREAD

**Issue by UntotaufUrlaub** [asahi417/lmppl#4]
Hi,

how is input text handled which is longer than allowed for the selected LM, is it truncated or is a [sliding window](https://huggingface.co/docs/transformers/perplexity) applied?

kind regards

**Comment by asahi417** [comment]
First of all, the url you've linked to the `sliding window` (https://huggingface.co/docs/transformers/perplexity) is explaining the standard way of computing perplexity with autoregressive LMs (GPT, OPT, etc), which actually truncates the overflow tokens (the tokens exceed the max_length), so it's not using `sliding window` to handle the overflow tokens. With autoregressive LMs, we compute loglikelihood of each token from left to right, conditioned on the precedent tokens, and that's what the introduction meant by `sliding window`.

Finally, the implementation of `lmppl` follows exactly same way as described in the introduction. So, you can get perplexity with `lmppl` as described in the introduction you've shared, but it truncates the overflow token so the method described in the introduction does.

**Comment by asahi417** [comment]
Sorry but I didn't check the last part of the blog. To be precise, we don't use the sliding window. The overflow token will be disregard.

**Comment by asahi417** [comment]
This actually looks interesting. If you have any resource (paper or blog), verifying the use of the sliding window such as testing on some benchmarks, please share it with us.

**Comment by UntotaufUrlaub** [comment]
Thanks for the information!
I got no resources, the explanation of huggingface just seems reasonable to me. Maybe consider adding it as optional for now, so the user can decide whether it is justified.

kind regards
